[book]
authors = ["Joseph Averbukh", "Stepan Parunashvili"]
language = "en"
multilingual = false
src = "web_content"
title = "Senior Engineer Jobsearch"

[build]
build-dir = "web_build"
create-missing = false

[output.html]
google-analytics = "UA-85735847-3"
git-repository-url = "https://github.com/nezaj/jobsearch-content"
git-repository-icon = "fa-github"
additional-css = ["theme/custom.css"]